plot(Energy$dateTime,Energy$Sub_metering_1,type = "l",ylab = "Energy sub meeting",xlab = "")
points(Energy$dateTime,Energy$Sub_metering_2,type = "l",col="red")
points(Energy$dateTime,Energy$Sub_metering_3,type = "l",col="blue")
legend("topright",col=c("black","blue","red"),lwd=c(1,1,1),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,"plot3.png",width=480,height=480)
dev.off()